### ISSUE TITLE
Implement instruction ORA

### ISSUE THREAD

**Issue by johnor** [evilcorpltd/n_e_s#167]
https://www.c64-wiki.com/wiki/ORA

**Comment by sa12123** [comment]
@johnor Working on it!

**Comment by johnor** [comment]
@sa12123 
Two opcodes were actually missing from the list in Opcode.h:

0x01 | Indexed-indirect
0x11 | Indirect-indexed
See here: https://www.c64-wiki.com/wiki/ORA
